apiVersion: v1
kind: Pod
metadata:
  name: affinity-preferred-demo
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: env
                operator: In
                values:
                  - prod
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

