apiVersion: v1
kind: Pod
metadata:
  name: anti-affinity-demo
  labels:
    app: anti-demo
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - ns-demo
          topologyKey: "kubernetes.io/hostname"
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

