apiVersion: apps/v1
kind: Deployment
metadata:
  name: aa-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aa-demo
  template:
    metadata:
      labels:
        app: aa-demo
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - aa-demo
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nginx
        image: nginx

