apiVersion: apps/v1
kind: Deployment
metadata:
  name: sec-demo

spec:
  replicas: 2
  selector:
    matchLabels:
      app: sec-demo
  template:
    metadata:
      labels:
        app: sec-demo
    spec:
      containers:
        - name: app
          image: busybox
          command: ["sh","-c","sleep 3600"]
          envFrom:
            - secretRef:
                name: demo-secret
