apiVersion: v1
kind: Pod
metadata:
    name: curl
    labels:
      app: curl
spec:
  restartPolicy: Never
  containers:
    - name: curl
      image: busybox:1.36
      command: ["sh", "-c", "sleep 3600"]
