apiVersion: v1
kind: Pod
metadata:
  name: vol-demo
spec:
  containers:
    - name: writer
      image: busybox
      command: ["sh", "-c", "echo 'hello from writer' > /data/msg && sleep 3600"]
      volumeMounts:
        - name: shared-storage
          mountPath: /data

    - name: reader
      image: busybox
      command: ["sh", "-c", "cat /data/msg || sleep 5"]
      volumeMounts:
        - name: shared-storage
          mountPath: /data

  volumes:
    - name: shared-storage
      emptyDir: {}

