apiVersion: v1
kind: Pod
metadata:
  name: ngijen
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
    - name: jenkins
      image: jenkins
      ports:
        - containerPort: 8080
