apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: app
      image: busybox
      command: ["sh", "-c", "echo 'persistent data' > /data/out.txt && sleep 3600"]
      volumeMounts:
        - name: myvol
          mountPath: /data
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: pvc-demo

