apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: siva-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: siva-app
  template:
    metadata:
      name: nginx-nodeaffinity-preferreds
      labels:
        app: siva-app
    spec:
      containers:
      - name: nginx
        image: nginx:stable
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: zone
                operator: In
                values:
                - black
                - red
