apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-preferred
spec:
  containers:
  - name: nginx
    image: nginx:stable
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - blue
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-preffered-1
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: zone
              operator: In
              values:
              - blue
              - red

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-preferred-2
spec:
  containers:
  - name: nginx
    image: nginx:stable
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - black

