apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector
spec:
  containers:
  - name: nginx
    image: nginx:stable
  nodeSelector:
    zone: blue


---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselector-1
spec:
  containers:
  - name: nginx
    image: nginx
  nodeSelector:
    zone: black
