apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-required
spec:
  containers:
  - name: nginx
    image: nginx:stable
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - blue
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeaffinity-required-1
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: zone
              operator: In
              values:
              - red
