apiVersion: v1
kind: Pod
metadata:
  name: test-tolerate-prod
spec:
  containers:
  - name: c
    image: nginx
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "prod"
    effect: "NoSchedule"
