apiVersion: v1
kind: Pod
metadata:
  name: no-toleration-pod
spec:
  containers:
  - name: c
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: tolerate-brief
spec:
  containers:
  - name: c
    image: nginx
  tolerations:
  - key: "special"
    operator: "Equal"
    value: "evict"
    effect: "NoExecute"
    tolerationSeconds: 30

