apiVersion: v1
kind: Pod
metadata:
  name: aff-pref
  labels:
    test: aff-pref
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - green

