apiVersion: v1
kind: Pod
metadata:
  name: demo-tol
spec:
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "prod"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx

