apiVersion: v1
kind: Pod
metadata:
  name: nginx-pvc-test
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["/bin/sh","-c"]
    args:
      - sleep 3600
    volumeMounts:
    - name: data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: nginx-pvc
